<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fecha fin vigencia_consultarInformacionBasica_formtablaEntidadesAPV0j_idt669</name>
   <tag></tag>
   <elementGuidId>5fd836ba-c3cf-4114-a88f-a2106df1f1fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[46]/span/div/div/table/tbody/tr/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5feb5104-743f-4525-b555-374135256996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consultarInformacionBasica_form:tablaEntidadesAPV:0:j_idt669</value>
      <webElementGuid>0b715205-1f91-4825-b314-f458d9fc27eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f4241277-65f3-4ec0-9ac3-b018eee04518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-icon-deleted</value>
      <webElementGuid>4649244a-f104-4b79-96b7-482fc572d994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;consultarInformacionBasica_form:tablaEntidadesAPV:0:j_idt669&quot;,f:&quot;consultarInformacionBasica_form&quot;,u:&quot;consultarInformacionBasica_form&quot;});return false;</value>
      <webElementGuid>205fd16f-218c-47de-bd66-5c86e0859064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;consultarInformacionBasica_form:tablaEntidadesAPV:0:j_idt669&quot;,type:&quot;dialog&quot;,escape:true,header:&quot;Eliminar&quot;,message:&quot;Desea eliminar el   registro?&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>3db0b039-ec2b-4f54-a7b1-b7df62d5104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consultarInformacionBasica_form:tablaEntidadesAPV:0:j_idt669&quot;)</value>
      <webElementGuid>8ec626d8-948b-4844-b082-189c87d76724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='consultarInformacionBasica_form:tablaEntidadesAPV:0:j_idt669']</value>
      <webElementGuid>40e9bff0-688d-43ac-827d-01973f10a968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='consultarInformacionBasica_form:tablaEntidadesAPV_data']/tr/td[5]/a</value>
      <webElementGuid>13c7fd75-44e7-433a-aa23-963f2c4cd520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[68]</value>
      <webElementGuid>aa661e56-1e15-468f-9d13-a849ee10fdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[46]/span/div/div/table/tbody/tr/td[5]/a</value>
      <webElementGuid>ecf3e508-ef80-42de-bc0e-12257c8a42c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'consultarInformacionBasica_form:tablaEntidadesAPV:0:j_idt669' and @href = '#']</value>
      <webElementGuid>81e482a2-7e6a-4e26-ac1e-b89144f37b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
