<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Descargar</name>
   <tag></tag>
   <elementGuidId>7cfd720c-d0b1-4a3b-b41f-1e9c7b7f55c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-radiobutton-icon.ui-icon.ui-icon-blank.ui-c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>
//table/tbody/tr[2]/td/div/div[2]/table/tbody/tr/td[1]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f31cf9a-de68-4260-a16b-a2027532e4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-radiobutton-icon ui-icon ui-icon-blank ui-c</value>
      <webElementGuid>8ae11140-472e-404a-8f84-bf8823f589c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupReporte:j_idt1983&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;ui-radiobutton ui-widget&quot;]/div[@class=&quot;ui-radiobutton-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-radiobutton-icon ui-icon ui-icon-blank ui-c&quot;]</value>
      <webElementGuid>2a253167-4c64-497f-8341-6cb8bf20682e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='popupReporte:j_idt1983']/tbody/tr/td/div/div[2]/span</value>
      <webElementGuid>866f074c-d28e-4082-ad55-3a31246afcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div[2]/table/tbody/tr/td/div/div[2]/span</value>
      <webElementGuid>f40f2058-76d5-41b1-998e-ad9ddb7a9c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
