<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Descargar - Copy</name>
   <tag></tag>
   <elementGuidId>6a952605-01cc-418c-85fc-ccede5c3ab1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/span/form[32]/div/div[2]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td[1]/table/tbody/tr/td/a
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-radiobutton-icon.ui-icon.ui-icon-blank.ui-c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed70070e-5b08-4b94-9fd7-b429f1e5f2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-radiobutton-icon ui-icon ui-icon-blank ui-c</value>
      <webElementGuid>0bad3c8a-8a0d-4de4-84dc-2dbc6b240e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupReporte:j_idt1983&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;ui-radiobutton ui-widget&quot;]/div[@class=&quot;ui-radiobutton-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-radiobutton-icon ui-icon ui-icon-blank ui-c&quot;]</value>
      <webElementGuid>3b51a12f-b6d4-468b-b0a9-dbe8d05ea9b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='popupReporte:j_idt1983']/tbody/tr/td/div/div[2]/span</value>
      <webElementGuid>2648635f-93e3-496d-9775-f7d2b750491c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div[2]/table/tbody/tr/td/div/div[2]/span</value>
      <webElementGuid>fbfc8793-d704-4e96-b050-d5b1c593107a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
