<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ACTIVO_listadoEmpleadoPrime_formtablaEmpleados0j_idt136</name>
   <tag></tag>
   <elementGuidId>8eac18d4-9c35-4c41-9faa-09b2ebc90db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1abce10-8766-47ca-a5e8-ec965531f271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt136</value>
      <webElementGuid>afea4b07-4421-4823-87f4-30dc9be6023a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6c9c59e8-410c-4781-93bb-2c90a85ecbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-icon-ver us-color-white us-iconos-card-colaborador us-hover-active</value>
      <webElementGuid>1f82a73b-7afc-496e-bb92-77cf82ac2f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ver</value>
      <webElementGuid>6a114018-0fed-422d-8731-5bb03684e836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('listadoEmpleadoPrime_form',{'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt136':'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt136'}).submit('listadoEmpleadoPrime_form');return false;</value>
      <webElementGuid>b0b7e2d1-1626-440c-ba3d-f5cdf4a7dfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver</value>
      <webElementGuid>6e3ef1f6-087f-494f-b6bb-85ba8ad5119b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt136&quot;)</value>
      <webElementGuid>b78a3ed2-38f2-4b11-b59a-d4be6db4d0d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt136']</value>
      <webElementGuid>bfd51a05-5641-480e-a491-d03f9259e591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='listadoEmpleadoPrime_form:tablaEmpleados_data']/tr/td/div/div[2]/div/a</value>
      <webElementGuid>bf578f6a-c0c0-402c-b7d6-60d845624315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>1c825fbf-07fc-484a-bf0f-466b53158f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>061db2ee-8f6d-4834-ad2c-0d26ed083992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt136' and @href = '#' and @title = 'Ver']</value>
      <webElementGuid>1fe2f2c5-c5fc-404f-a53a-a13b92966e49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
