<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Administrador_masivo_cerrar_menu</name>
   <tag></tag>
   <elementGuidId>e3f6a612-692f-44a9-8357-4eaf7d8b733f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cerrar_menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id = 'cerrar_menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9f7de05-f3ca-4ba8-9712-8c29f5d635a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cerrar_menu</value>
      <webElementGuid>6ee5ff83-3d97-43c7-a17f-9d921c744bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-chevron-right us-cl-primario us-boton-menu movimiento</value>
      <webElementGuid>ee9c310c-6613-447f-87dc-acd40e03da41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cerrar_menu&quot;)</value>
      <webElementGuid>cdc47569-4e0a-4fae-bff1-126056fb6de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cerrar_menu']</value>
      <webElementGuid>b1046cca-9e6e-4f5b-83fe-aa6072f0479c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='j_idt71']/div/a</value>
      <webElementGuid>d9931bd8-57b4-4275-9045-e2d6ec471d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>105c34dc-e159-4ed4-9bd3-889dd086e484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cerrar_menu']</value>
      <webElementGuid>e3ac37a2-e1c1-4805-8a2e-02ffa60f06ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
