<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Guardar</name>
   <tag></tag>
   <elementGuidId>b9bc12ce-ca4f-46da-939e-fef26bedbfe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Guardar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fadff2dc-baca-4853-ac20-37c6fc84ae87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_solicitudesEmpleado:tabsSolicitudesDetalle:j_idt411</value>
      <webElementGuid>9419a645-65b4-4135-9c82-bfde9fff8b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a169ae21-f5a7-4d60-bff8-4539698b6d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton</value>
      <webElementGuid>38000432-2f7e-4940-a447-6e6e37e89b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_solicitudesEmpleado:tabsSolicitudesDetalle:j_idt411&quot;,f:&quot;form_solicitudesEmpleado&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>ef5d2768-3333-4ba5-9610-50ae9cbc1e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>21ed493f-233b-4df5-a7f0-307fd48fa036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_solicitudesEmpleado:tabsSolicitudesDetalle:j_idt411&quot;)</value>
      <webElementGuid>8b44233f-9fb3-4173-ab5e-8d36ae3e5bc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_solicitudesEmpleado:tabsSolicitudesDetalle:j_idt411']</value>
      <webElementGuid>5a02c16d-8f1c-4098-8274-830b917b300c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_solicitudesEmpleado:tabsSolicitudesDetalle:j_idt199']/div/table[2]/tbody/tr/td/a</value>
      <webElementGuid>b2d492bd-2503-4734-a08b-bcad853d00e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Guardar')]</value>
      <webElementGuid>e0ed4084-cc4f-4e9d-b612-cd42f8c2c0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[1]/following::a[1]</value>
      <webElementGuid>2c86f818-dc8b-47d8-95fb-f754601d5d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::a[1]</value>
      <webElementGuid>4693cd65-aaee-41eb-a3e1-abb1e392cc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte Técnico'])[1]/preceding::a[2]</value>
      <webElementGuid>ce91dc1c-e41f-447c-bd62-0dc2526b2960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asistente'])[1]/preceding::a[3]</value>
      <webElementGuid>967c72d6-a524-428d-a943-5f2f440149e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar']/parent::*</value>
      <webElementGuid>21fe7879-8642-4c01-a563-48300b1cbb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[31]</value>
      <webElementGuid>01e8e5dc-34fb-4dcd-9709-4938967d605d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>f268f510-392a-47d5-876f-8a13a948f962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_solicitudesEmpleado:tabsSolicitudesDetalle:j_idt411' and @href = '#' and (text() = 'Guardar' or . = 'Guardar')]</value>
      <webElementGuid>9756d70b-35a4-4da6-8110-23f97e7f1256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
