<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>embed_ Doc</name>
   <tag></tag>
   <elementGuidId>2329761b-4640-4c08-9b5d-a991b3f0cf8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div[2]/div[3]/div/div/div/div/div/div/table[3]/tbody/tr/td/center/embed
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>73b102b8-75fb-4eb1-ab02-a8b7a537d381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1683660543158</value>
      <webElementGuid>047e9760-66cd-445c-894d-a28975100228</webElementGuid>
   </webElementProperties>
</WebElementEntity>
