<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Certifica Laboral - Copy</name>
   <tag></tag>
   <elementGuidId>e78ecd62-b245-45cf-a12a-dc4c05a28ad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.ui-widget-content.ui-datatable-odd.ui-datatable-selectable.ui-state-hover > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/div[2]/div[3]/div/div/div/div/div[1]/div/div/div/table/tbody/tr[2]/td[1]/span
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>04ac9a93-8798-411c-a458-04406bc668df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>3d115eab-ad11-4743-bc8a-ade82d8aa5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Certifica Laboral</value>
      <webElementGuid>14c69f68-6ac3-4531-b341-7e5f5c236702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_solicitudesEmpleado:tabsSolicitudes:j_idt186_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-odd ui-datatable-selectable ui-state-hover&quot;]/td[1]</value>
      <webElementGuid>5a067e7a-529c-491f-b3c2-6e7eef730021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='form_solicitudesEmpleado:tabsSolicitudes:j_idt186_data']/tr[2]/td</value>
      <webElementGuid>17a632c5-ceee-4d98-bf2d-84c592b6abb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERTIFICACIÓN LABORAL (CON SUELDO)'])[1]/following::td[1]</value>
      <webElementGuid>a9bb2fa8-e58b-4513-a8c0-32ebbdf50076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certifica Laboral'])[1]/following::td[2]</value>
      <webElementGuid>d4edeaec-6902-420f-879f-9ba403f7936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERTIFICACIÓN LABORAL (SIN SUELDO)'])[1]/preceding::td[1]</value>
      <webElementGuid>20f06607-a6e7-416b-988e-4bbca5d09096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>62a703ca-7cbd-4911-b8cb-8870646e0ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Certifica Laboral' or . = 'Certifica Laboral')]</value>
      <webElementGuid>d910ed19-1ad5-44b8-ab07-e233f74c89fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
