<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Certifica Laboral</name>
   <tag></tag>
   <elementGuidId>a4c1806d-4f81-4a09-81f6-fa55c1582944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.ui-widget-content.ui-datatable-odd.ui-datatable-selectable.ui-state-hover > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/span/div[2]/form/div[2]/div[3]/div/div/div/div/div[1]/div/div/div/table/tbody/tr[1]/td[1]/span
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bbae1c4a-7fe2-4283-90f9-468934f77d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>228b95fe-dd82-4cdc-8e7e-3f35ee46cb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Certifica Laboral</value>
      <webElementGuid>065f49f1-ea87-448e-addc-d782aecd1a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_solicitudesEmpleado:tabsSolicitudes:j_idt186_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-odd ui-datatable-selectable ui-state-hover&quot;]/td[1]</value>
      <webElementGuid>f8b04b68-12f9-41cb-aefb-496a7ecfa792</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='form_solicitudesEmpleado:tabsSolicitudes:j_idt186_data']/tr[2]/td</value>
      <webElementGuid>3c5b4069-a1f6-4106-919d-9dcdd371d647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERTIFICACIÓN LABORAL (CON SUELDO)'])[1]/following::td[1]</value>
      <webElementGuid>0746600f-5383-4c18-952f-77fee2483c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certifica Laboral'])[1]/following::td[2]</value>
      <webElementGuid>0c717132-67ab-40b6-9eb6-92190956460e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERTIFICACIÓN LABORAL (SIN SUELDO)'])[1]/preceding::td[1]</value>
      <webElementGuid>483bb812-f66d-415f-be33-c5443eb1bd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>58d00d00-3dc2-4be9-b8f4-47358e7f4e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Certifica Laboral' or . = 'Certifica Laboral')]</value>
      <webElementGuid>cc3ffd97-1575-45d1-88bc-cd35aa90eb20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
