<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Administrador_masivo_cerrar_menu</name>
   <tag></tag>
   <elementGuidId>98948412-4066-43a0-9a81-3fc43a9a1f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cerrar_menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce1d1567-0bf0-4183-8162-5ba018d0865a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cerrar_menu</value>
      <webElementGuid>e0bd6e34-1565-4776-b0b8-5a610a5bf0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-chevron-right us-cl-primario us-boton-menu movimiento</value>
      <webElementGuid>f14fecd8-9b23-4cc2-8eb8-513cd8139416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cerrar_menu&quot;)</value>
      <webElementGuid>2247e9e3-c00d-4df7-924f-b825379fbc70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cerrar_menu']</value>
      <webElementGuid>dfcbdefe-7355-4520-81ee-3492b4ad7c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='j_idt71']/div/a</value>
      <webElementGuid>37d8a0e7-a058-44e6-9c37-2f3b36484570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>fbf01d4d-dd54-4e62-b443-975556aa6ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cerrar_menu']</value>
      <webElementGuid>be650e2c-9441-4ae1-917b-96f1ce8948fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
