<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Descargar3</name>
   <tag></tag>
   <elementGuidId>9f47c43e-aeb6-4544-a225-f3dc68357e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.us-boton.btn-descargar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Descargar')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>868bf214-1539-42d8-a3bf-460d25fef718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/saraprimeweb/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc31c34c32c37c33c31c36c35c37c38c39c66c34c33c36c62c61c37c31c32c32c38c64c38c61c34c32c35c36c61c38c31&amp;E=Reporte_Nomina_Electr%C3%B3nica.xlsx</value>
      <webElementGuid>3f348059-ff65-4451-847c-98a6ec747220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_black</value>
      <webElementGuid>7b6090fc-bef0-4ba3-9df4-5601bce06c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-boton  btn-descargar</value>
      <webElementGuid>049c30d1-0f57-4bfa-93d9-202f655be673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descargar</value>
      <webElementGuid>8b60fa3b-9e70-47cc-88d2-bd868decd637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupReporte:dialogPopupReporte_content&quot;)/table[@class=&quot;popupBody&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;us-boton  btn-descargar&quot;]</value>
      <webElementGuid>496c9dc2-a9ea-4681-9c58-78b8a71e0403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupReporte:dialogPopupReporte_content']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>3526dda0-6595-4813-8c16-c3a4f5c18973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Descargar')])[3]</value>
      <webElementGuid>f9509c20-0b0f-4179-ba14-6e3c031996a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes Generales'])[1]/following::a[1]</value>
      <webElementGuid>aca5aab3-58e2-46da-a4e2-8caf0be7e725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::a[2]</value>
      <webElementGuid>5e11f7ee-9dc6-481c-8e96-889f2b611c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte Técnico'])[1]/preceding::a[2]</value>
      <webElementGuid>a99eae49-8dfb-4480-9fa8-2d1c45b33e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Union Soluciones© 2019'])[1]/preceding::a[3]</value>
      <webElementGuid>731f3e8d-640b-43bd-9732-52509ad8ed02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/saraprimeweb/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc31c34c32c37c33c31c36c35c37c38c39c66c34c33c36c62c61c37c31c32c32c38c64c38c61c34c32c35c36c61c38c31&amp;E=Reporte_Nomina_Electr%C3%B3nica.xlsx')]</value>
      <webElementGuid>0bc47177-5f13-4f38-961f-cf2217493494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>fb5274e8-5dea-43b1-8f91-61e4378ac0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/saraprimeweb/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc31c34c32c37c33c31c36c35c37c38c39c66c34c33c36c62c61c37c31c32c32c38c64c38c61c34c32c35c36c61c38c31&amp;E=Reporte_Nomina_Electr%C3%B3nica.xlsx' and (text() = 'Descargar' or . = 'Descargar')]</value>
      <webElementGuid>7576e102-b50c-43b3-b68b-70f77b5d4802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
