<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Inicial_popupReportetablaParametroReporte0fecha_input</name>
   <tag></tag>
   <elementGuidId>043ee083-8bd0-4b23-8c36-e40817d4cf19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ae23bf7-ab21-49a3-9e46-3be8977dfa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupReporte:tablaParametroReporte:0:fecha_input</value>
      <webElementGuid>686a8576-84ca-44bb-9a55-12500c924e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupReporte:tablaParametroReporte:0:fecha_input</value>
      <webElementGuid>00c8808d-2f25-4e54-9e72-a548b2e999b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>883388f7-eb0c-47e1-8c13-fa50f33f3e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker ui-state-focus ui-state-hover</value>
      <webElementGuid>c21e558a-a1b1-4a23-b918-8a947447fe73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>c24f2acf-0128-4a87-890c-5a9d46b5dcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;popupReporte:tablaParametroReporte:0:fecha&quot;,e:&quot;valueChange&quot;,f:&quot;popupReporte&quot;,p:&quot;popupReporte:tablaParametroReporte:0:fecha&quot;,u:&quot;popupReporte:tablaParametroReporte:0&quot;});</value>
      <webElementGuid>3285c822-4f90-4ddf-905f-8ba7289abf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>18a8a975-edfd-4769-bc83-d729de2f9c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce52ec40-09e5-48c9-a925-082815a15cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df016b14-c776-4aa6-b1e5-3802f839be40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupReporte:tablaParametroReporte:0:fecha_input&quot;)</value>
      <webElementGuid>3b5947f2-64d6-4035-9174-76e42b5b233d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popupReporte:tablaParametroReporte:0:fecha_input']</value>
      <webElementGuid>c4704ead-278b-4377-b80a-6b622916d07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='popupReporte:tablaParametroReporte:0:fecha']/input</value>
      <webElementGuid>ea5d7f44-a513-4931-ae21-cc62a0dcbb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>89c83d8d-d140-42a4-847f-808fd93fa23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popupReporte:tablaParametroReporte:0:fecha_input' and @name = 'popupReporte:tablaParametroReporte:0:fecha_input' and @type = 'text' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>cd505680-58f0-4c11-9784-4f65386e735c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
