<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Corte_listado_nominaelectronicaj_idt95</name>
   <tag></tag>
   <elementGuidId>cd22e51e-f159-4948-b86a-0a64121a29eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1adef6da-c555-4083-bbad-7e73c690b6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listado_nominaelectronica:j_idt95</value>
      <webElementGuid>37620d3c-b540-4fc3-afdd-47e190d48152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listado_nominaelectronica:j_idt95</value>
      <webElementGuid>6a5b5604-371a-4fc9-bb73-b2b2f26fd46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fd8ec71-5c61-4ac6-b0b5-4e07277c760f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>6f35a439-4354-4549-91dc-47c8d491341f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ace_valor_campo_estandar ui-state-filled ui-state-hover ui-state-focus</value>
      <webElementGuid>0fe9d853-43cc-4326-874e-19700769af30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2de1eaa7-9779-4878-9df6-098c6f4d76fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f1ef7e17-6134-4fe5-a064-8eb522e8d7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>525d877c-f0e5-4eb1-bdac-865c3811c80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;listado_nominaelectronica:j_idt95&quot;,e:&quot;valueChange&quot;,f:&quot;listado_nominaelectronica&quot;,p:&quot;listado_nominaelectronica:j_idt95&quot;,u:&quot;listado_nominaelectronica:listaNominaElectronica&quot;});</value>
      <webElementGuid>1811957f-c11a-434f-9951-e7f1675dddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1539a7aa-3ec2-4e5e-bf0b-a35aaeab1007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9c4796c-f0bc-4a4e-8072-5b9c78d88f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4d77a6b-9dae-48fe-9218-175bacffa8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listado_nominaelectronica:j_idt95&quot;)</value>
      <webElementGuid>aa725586-7cee-4894-a736-04a62825a8ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='listado_nominaelectronica:j_idt95']</value>
      <webElementGuid>540b7b1e-2f9f-43b4-af2a-84e299d6ce6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listado_nominaelectronica:formPanel_content']/table/tbody/tr/td[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>65daa342-dc0f-4669-9569-57f778984031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>fe65463d-38ee-4565-b004-e80225bb22d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'listado_nominaelectronica:j_idt95' and @name = 'listado_nominaelectronica:j_idt95' and @type = 'text']</value>
      <webElementGuid>cbd4e56c-c5f9-4869-9b34-c118f310bc9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
