<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1654008107142</name>
   <tag></tag>
   <elementGuidId>f2c93bb0-752f-4aa7-a03e-a93089826160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[7]/a
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8f3a3b19-3ac0-4ecc-a313-1ec6dbaeb3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1654008107142</value>
      <webElementGuid>01a9b63c-5bdf-48d4-8818-6efc2b8821cf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
