<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nombres_consultarInformacionBasica_formj_idt183</name>
   <tag></tag>
   <elementGuidId>23c0a7b4-c41c-4836-b7dd-ffd3a743a15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7a9fcd8-a932-48ec-b77f-41507345e6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consultarInformacionBasica_form:j_idt183</value>
      <webElementGuid>2896d677-94aa-4279-b7ad-a0eabb817692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>58a6ff19-2432-487a-9026-bff5b2a5f6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-icon-edit</value>
      <webElementGuid>cde267c5-34b1-4d9e-96de-d54eefe4a91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;consultarInformacionBasica_form:j_idt183&quot;,f:&quot;consultarInformacionBasica_form&quot;,u:&quot;consultarInformacionBasica_form:nombres&quot;});return false;</value>
      <webElementGuid>b8e6e9be-0587-47c8-ba9a-94d39f599553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consultarInformacionBasica_form:j_idt183&quot;)</value>
      <webElementGuid>511485a4-043a-4637-9040-4460faa8985c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='consultarInformacionBasica_form:j_idt183']</value>
      <webElementGuid>6ddc1403-d519-4a32-ad9f-4d0c97c45edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='consultarInformacionBasica_form:nombres']/div[3]/a</value>
      <webElementGuid>a9682207-eab4-44c0-8a02-8b8a221aeb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>f02fee42-5bc3-4676-b2c9-7ee24c5bdb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>00277993-8c49-48f2-8210-ff7d99dcba77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'consultarInformacionBasica_form:j_idt183' and @href = '#']</value>
      <webElementGuid>14f2c51e-9bc1-4e7f-8058-6dd9d64f799f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
