<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PENSION_formulario_nominaj_idt3205verCambioEmpleado6</name>
   <tag></tag>
   <elementGuidId>973eb3a7-e5e8-4f07-aca6-a664c43085e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[6]/td[7]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>586effe3-1e75-4228-88a4-43e52e9be0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:5:verCambioEmpleado</value>
      <webElementGuid>8c2c3db9-ffa9-4bb3-8351-830318490092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0326a5c1-5c4e-4f10-923f-c3cc46293965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-user-add</value>
      <webElementGuid>140aa067-14d3-4e6b-ab2e-20f2c547a6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('formulario_nomina',{'formulario_nomina:j_idt320:5:verCambioEmpleado':'formulario_nomina:j_idt320:5:verCambioEmpleado','empleadoVer':'co.com.unionsoluciones.saraprime.logica.dto.EmpleadoPeriodoNominaDTO@531452a8'}).submit('formulario_nomina');return false;</value>
      <webElementGuid>e7cd1008-6e1b-4fdc-9e50-888d7cc251b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:5:j_idt347</value>
      <webElementGuid>e1e5ccc5-2fa7-47c6-9613-1bfadd7e410c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_nomina:j_idt320:5:verCambioEmpleado&quot;)</value>
      <webElementGuid>b4accb5c-62ed-4acd-8acd-099349c8f951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formulario_nomina:j_idt320:5:verCambioEmpleado']</value>
      <webElementGuid>81d8ee58-eede-41ec-8c30-f1637e14fd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formulario_nomina:j_idt320_data']/tr[6]/td[7]/a[3]</value>
      <webElementGuid>61ef75f7-6da7-4c4c-b937-971f9f99da94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[63]</value>
      <webElementGuid>1431f0b6-93b5-4d9a-a32d-c0d262b11b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[7]/a[3]</value>
      <webElementGuid>e1509815-60f5-445f-a5fe-4f50888a6877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formulario_nomina:j_idt320:5:verCambioEmpleado' and @href = '#']</value>
      <webElementGuid>a6e0d1f9-63ad-4e8c-b5fb-04e2c93453e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
