<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PENSION_formulario_nominaj_idt3203verCambioEmpleado</name>
   <tag></tag>
   <elementGuidId>3991df4c-00b2-4557-8025-f756496c28a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[4]/td[7]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>daf70726-5500-4a69-b839-479c6614d377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:3:verCambioEmpleado</value>
      <webElementGuid>77aa93cd-31b7-4e05-b5ad-2ea751d824dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3ea682d6-394f-4b5e-84fa-a309eb1c5cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-user-add</value>
      <webElementGuid>002cd983-b5ba-4921-8c8c-b7a26fc3f7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('formulario_nomina',{'empleadoVer':'co.com.unionsoluciones.saraprime.logica.dto.EmpleadoPeriodoNominaDTO@37b4ae43','formulario_nomina:j_idt320:3:verCambioEmpleado':'formulario_nomina:j_idt320:3:verCambioEmpleado'}).submit('formulario_nomina');return false;</value>
      <webElementGuid>57b610bb-9651-4dec-80ef-af95da13fcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:3:j_idt347</value>
      <webElementGuid>fd292fb2-d5a5-4476-8d26-dd238b89b3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_nomina:j_idt320:3:verCambioEmpleado&quot;)</value>
      <webElementGuid>eeb73160-ec8a-462f-8010-af4f4d43fc55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formulario_nomina:j_idt320:3:verCambioEmpleado']</value>
      <webElementGuid>a89a9699-1954-4bad-85a6-78e7fee48f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formulario_nomina:j_idt320_data']/tr[4]/td[7]/a[3]</value>
      <webElementGuid>1f161135-ffd7-467d-9cb6-b4c373d56dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[51]</value>
      <webElementGuid>8fb44896-855d-4eaa-865d-71bec8b41b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[7]/a[3]</value>
      <webElementGuid>b6ee55b0-69bf-4748-b1b9-dcfd75a4847e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formulario_nomina:j_idt320:3:verCambioEmpleado' and @href = '#']</value>
      <webElementGuid>ed399093-5a37-478e-bc38-7e4d23dbf4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
