<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Regresar a nomina</name>
   <tag></tag>
   <elementGuidId>852c187f-08fd-4b08-9bfe-48582858d3e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Regresar a nomina')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f623b8f0-0bab-40e9-83a8-f8b8fdac5971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consultarInformacionBasica_form:j_idt699</value>
      <webElementGuid>a8fdf2c0-f0ee-43a1-824d-0ff858ebc593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8c4706cb-e39a-4125-8ac6-2050ee6ea12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton</value>
      <webElementGuid>ba2e08f3-70a5-4ac5-8f6e-335821db029e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('consultarInformacionBasica_form',{'consultarInformacionBasica_form:j_idt699':'consultarInformacionBasica_form:j_idt699'}).submit('consultarInformacionBasica_form');return false;</value>
      <webElementGuid>94e176ff-5215-4285-ba74-b251bd0065a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Regresar a nomina</value>
      <webElementGuid>1c4d3388-0d7a-4958-b6ba-6d0a14b3c30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consultarInformacionBasica_form:j_idt699&quot;)</value>
      <webElementGuid>e21b7b4f-a06d-49cf-a181-7d1a89d68e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>851d3d5d-5e5f-44d2-9ca8-5604eee55b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consultarInformacionBasica_form:j_idt699</value>
      <webElementGuid>5adac854-cf4e-4c4b-bda7-250b2b040a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>24c6abb2-ba91-4a3f-bdb8-c282285dbaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton</value>
      <webElementGuid>4e242810-0d49-43fd-bf31-b2d605c8602b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('consultarInformacionBasica_form',{'consultarInformacionBasica_form:j_idt699':'consultarInformacionBasica_form:j_idt699'}).submit('consultarInformacionBasica_form');return false;</value>
      <webElementGuid>b1ff0a36-5024-4502-86e1-141e216ab4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Regresar a nomina</value>
      <webElementGuid>d3bdabe2-07ce-43fa-94d4-308f96c2ecc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consultarInformacionBasica_form:j_idt699&quot;)</value>
      <webElementGuid>705fd95d-8cd0-4b9a-917e-dfb20561a28c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='consultarInformacionBasica_form:j_idt699']</value>
      <webElementGuid>d9dac3b7-aa9f-4d24-b957-4c2f34699536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='consultarInformacionBasica_form']/div/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>fcb0608d-6958-4abc-8354-526c4f9d9eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Regresar a nomina')]</value>
      <webElementGuid>f79bec42-4351-47e0-8fad-b02ead342bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Información Tributaria'])[2]/following::a[1]</value>
      <webElementGuid>65316c64-0bf9-4913-8c2f-d3f6569fc4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Información Contratación'])[2]/following::a[2]</value>
      <webElementGuid>4851f1a6-d2e6-4b91-9fbe-4e88ad8bc66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte Técnico'])[1]/preceding::a[1]</value>
      <webElementGuid>68f1ab32-294b-4c02-9aef-94eac93672c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Union Soluciones© 2019'])[1]/preceding::a[2]</value>
      <webElementGuid>62b3e79c-1df5-4fa0-babc-c5cfb0b393d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Regresar a nomina']/parent::*</value>
      <webElementGuid>81a0a36b-29be-4790-b3c2-d2b41c6965d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[77]</value>
      <webElementGuid>bd3538bc-94f6-42b6-bf87-4d0896e5358b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>f786123e-ca6f-466e-bc76-97845510b3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'consultarInformacionBasica_form:j_idt699' and @href = '#' and (text() = 'Regresar a nomina' or . = 'Regresar a nomina')]</value>
      <webElementGuid>44f9ef2f-9e68-4591-b62a-339967935ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
