<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_cerrar</name>
   <tag></tag>
   <elementGuidId>93248961-ab81-480c-af74-d29976091f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/span/form[39]/div/div[1]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>284872f2-cda4-42e2-81a6-5159863a1558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674058123694</value>
      <webElementGuid>dc0b8a34-d7d8-4d35-b6f1-734a0179c8f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
