<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nmina</name>
   <tag></tag>
   <elementGuidId>9b9d1805-663e-46cd-9769-1f94683144e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.crumbs > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2033136a-a658-4e23-bd81-e742e5a86b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d4d8413b-c708-443f-8523-8d845f693ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('form_breadcrumd'),{'form_breadcrumd:j_idt85:j_idt88':'form_breadcrumd:j_idt85:j_idt88'},'');return false</value>
      <webElementGuid>3caeef8a-a30a-4e6b-a024-69d982bcf90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nómina</value>
      <webElementGuid>e24b2aff-29ae-4291-b60b-a5f3a3bdc967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_breadcrumd&quot;)/div[@class=&quot;col-md-12&quot;]/div[1]/span[@class=&quot;crumbs&quot;]/a[1]</value>
      <webElementGuid>fd5a58a3-74e3-4908-9427-c91fcc9d99a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('form_breadcrumd'),{'form_breadcrumd:j_idt85:j_idt88':'form_breadcrumd:j_idt85:j_idt88'},'');return false&quot;]</value>
      <webElementGuid>e7683639-ed0d-4255-b100-09b54cdc5dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_breadcrumd']/div/div/span/a</value>
      <webElementGuid>246bd36c-6153-4968-af07-bccaab39114f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Nómina')])[3]</value>
      <webElementGuid>78b5dcb5-afef-4ff6-9968-a6681d8bfc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nómina'])[1]/following::a[1]</value>
      <webElementGuid>efce9e72-0125-49a1-a7c3-46edd467b16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba Boton De Pago'])[2]/following::a[10]</value>
      <webElementGuid>111c9f9b-b052-419e-88fa-e6dc3689d2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periodos aprobados'])[1]/preceding::a[8]</value>
      <webElementGuid>34910bcb-d8dd-41a7-aa60-0651513e7631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[14]</value>
      <webElementGuid>a4223b8a-ad3c-40f2-93b3-a9e65e68aa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>d8c7ce86-fbd0-49de-9904-5e11515442ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Nómina' or . = 'Nómina')]</value>
      <webElementGuid>9dc30123-9fb5-4398-a2c0-124b0ef9ad79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
