<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>br_fecha</name>
   <tag></tag>
   <elementGuidId>80bf3059-c557-4540-9eb5-31dae962a99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
/html/body/div[3]/div/div/div/div[2]/div[3]/div[3]/div/div[1]/div/div[3]/p[1]/br[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
