<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>br_Numero</name>
   <tag></tag>
   <elementGuidId>ecfc601c-7b8a-420d-a038-cb12173fffea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//div[3]/p[1]/br[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
