<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NOMINA  DICIEMBRE 2022_formulario_nominacbSiguientePeriodo</name>
   <tag></tag>
   <elementGuidId>ce9947c1-fc0c-4928-9385-019f5456ff63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formulario_nomina:cbSiguientePeriodo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6edd6e54-330e-4447-86c9-e045857cf30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_nomina:cbSiguientePeriodo</value>
      <webElementGuid>e0bc2389-c2d7-40a7-923c-22d111290efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4a0f9be9-dc2b-4482-8502-c68c0c2dacfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formulario_nomina:cbSiguientePeriodo</value>
      <webElementGuid>c77c516b-a682-4731-a53c-15b8a97c333e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Siguiente Periodo</value>
      <webElementGuid>242ef615-df21-4d46-9852-f16044099ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-boton</value>
      <webElementGuid>0696a3fb-b19b-4bcf-9788-4b87303cd205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_nomina:cbSiguientePeriodo&quot;)</value>
      <webElementGuid>4c092553-b139-4369-9595-21825e0b01a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formulario_nomina:cbSiguientePeriodo']</value>
      <webElementGuid>df7c1144-ec09-45de-ba54-9b033f96c71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formulario_nomina:j_idt164_content']/input</value>
      <webElementGuid>3bb1742c-cbf6-44f9-9418-eb8c6902a304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8b99d52a-3beb-49b4-b22b-5a0e08fec287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'formulario_nomina:cbSiguientePeriodo' and @type = 'submit' and @name = 'formulario_nomina:cbSiguientePeriodo']</value>
      <webElementGuid>249b8b27-b9c0-44f3-8285-41407748566e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
