<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha de Pago Prima Legal_popupPagoPrimaLegalfechaPrima_input</name>
   <tag></tag>
   <elementGuidId>79f54f9c-23a5-4e50-9b08-f19d7fd5f28b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>
//input[@id='popupPagoPrimaLegal:fechaPrima_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbc71a6e-995b-4672-a3cf-0c7da8e5859f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupPagoPrimaLegal:fechaPrima_input</value>
      <webElementGuid>3a9e7d40-c4f9-476c-b645-a656f18742d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupPagoPrimaLegal:fechaPrima_input</value>
      <webElementGuid>3cbc1258-981a-4298-b7ed-f1ea1f56f009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd9d33a5-9ef7-4bab-9c15-8b033e4e4e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker ui-state-hover ui-state-focus</value>
      <webElementGuid>79dc072e-6f5f-4aaa-891f-e91dfbbc8299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ea91a69c-5079-4f79-a535-393e1ff4b61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83130e67-ab94-4774-a59f-65991d9c5cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d7aafcc7-7c5e-4067-a514-077aaf567a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupPagoPrimaLegal:fechaPrima_input&quot;)</value>
      <webElementGuid>f91bb433-8472-46c8-9d33-7871178b3f50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popupPagoPrimaLegal:fechaPrima_input']</value>
      <webElementGuid>5f6753e5-027d-4cd0-97e9-59f9a753f39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='popupPagoPrimaLegal:fechaPrima']/input</value>
      <webElementGuid>642e56be-00c2-4bda-9240-fc2d31b64ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[17]/div/div[2]/div[2]/div[2]/span/input</value>
      <webElementGuid>625b8ddb-44c7-48c6-af77-1f784e8f4f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popupPagoPrimaLegal:fechaPrima_input' and @name = 'popupPagoPrimaLegal:fechaPrima_input' and @type = 'text']</value>
      <webElementGuid>dd868bad-916b-4706-b040-8ff2b2da7cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
