<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nmina</name>
   <tag></tag>
   <elementGuidId>08b5671b-1047-4f6f-840e-93408e351e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.crumbs > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2b8f662-d1d8-4025-b4f4-80bca36990b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>009c1a23-0440-4132-8b8b-1ff96abe224d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('form_breadcrumd'),{'form_breadcrumd:j_idt85:j_idt88':'form_breadcrumd:j_idt85:j_idt88'},'');return false</value>
      <webElementGuid>73a87836-4d74-43e1-aef1-a951efd41b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nómina</value>
      <webElementGuid>d00b03d4-3700-4a1d-a30f-bffea04742ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_breadcrumd&quot;)/div[@class=&quot;col-md-12&quot;]/div[1]/span[@class=&quot;crumbs&quot;]/a[1]</value>
      <webElementGuid>8948ef0c-f428-4063-bb57-2fb5b9069e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('form_breadcrumd'),{'form_breadcrumd:j_idt85:j_idt88':'form_breadcrumd:j_idt85:j_idt88'},'');return false&quot;]</value>
      <webElementGuid>ba4a0b3a-d750-418b-b72e-93199313e299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_breadcrumd']/div/div/span/a</value>
      <webElementGuid>ceecb64c-205b-4075-b54e-167fcb01f781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Nómina')])[3]</value>
      <webElementGuid>35a34d96-3b0e-4394-81f2-0d4153d3202d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nómina'])[1]/following::a[1]</value>
      <webElementGuid>e1d1fbb1-8a89-4b3d-9fb2-5def10e95066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insumos Medicos Comfama Sas*'])[2]/following::a[10]</value>
      <webElementGuid>446d55e2-cacd-4c69-a33a-fdd3b34c17ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle Periodo'])[1]/preceding::a[8]</value>
      <webElementGuid>94eefaaa-b05f-4e36-932d-073871ba516d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Pago:'])[1]/preceding::a[8]</value>
      <webElementGuid>fc19816e-9979-445d-ab8a-1483bbee8678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[14]</value>
      <webElementGuid>e08c1415-e5cb-48a8-8f7f-3af1dd1c4f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>c21ca21b-622e-42e7-a8ab-fb14cc99c1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Nómina' or . = 'Nómina')]</value>
      <webElementGuid>831f0d88-2c9f-4bd0-86f1-afa8e3b49a7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
