<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check</name>
   <tag></tag>
   <elementGuidId>951f5ee2-65f3-433a-a42b-5808851ac4dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/span/div/div/form[5]/div/div[3]/div/div/div[3]/div/div/table/tbody/tr[1]/td[9]/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c566fbed-ed42-4018-95bc-eb95f4e7626a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1653518256741</value>
      <webElementGuid>4f0fa9d5-60c6-445a-a84c-070d8dd1968d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
