<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check</name>
   <tag></tag>
   <elementGuidId>951f5ee2-65f3-433a-a42b-5808851ac4dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/span/div[2]/div/form[5]/div/div[3]/div/div/div[3]/div/div/table/tbody/tr[1]/td[9]/div/a[2]/span
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f1671033-362a-4d09-976b-49f7b95c5fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1653518256741</value>
      <webElementGuid>97100480-d468-417e-a98d-35c5ddbeab7c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
