<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ACTIVO_us-icon-remover</name>
   <tag></tag>
   <elementGuidId>49abf164-34bb-42a9-9ddc-6319def24f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.us-icon-remover.us-color-white.us-iconos-card-colaborador.us-hover-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Retirar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('listadoEmpleadoPrime_form'),{'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt275':'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt275','empleadoLiquidar':'co.com.unionsoluciones.saraprime.logica.dto.HojaEmpleadoDTO@17adb908'},'');return false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-icon-remover us-color-white us-iconos-card-colaborador us-hover-active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listadoEmpleadoPrime_form:tablaEmpleados_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even ui-datatable-selectable fila_tabla_ace&quot;]/td[1]/div[@class=&quot;us-w-100&quot;]/div[@class=&quot;col-md-1 col-sm-1 col-xs-1&quot;]/div[@class=&quot;button-bar button-bar-large&quot;]/a[@class=&quot;us-icon-remover us-color-white us-iconos-card-colaborador us-hover-active&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('listadoEmpleadoPrime_form'),{'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt275':'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt275','empleadoLiquidar':'co.com.unionsoluciones.saraprime.logica.dto.HojaEmpleadoDTO@17adb908'},'');return false&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='listadoEmpleadoPrime_form:tablaEmpleados_data']/tr/td/div/div[2]/div/a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
   </webElementXpaths>
</WebElementEntity>
