<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EN PROCESO DE LIQUIDACION_listadoEmpleadoPrime_formtablaEmpleados0j_idt140</name>
   <tag></tag>
   <elementGuidId>13a4e0b8-49ce-4ee8-b872-a2b8065985f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17be3842-af11-4f4b-953f-9d100db72f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt140</value>
      <webElementGuid>ac62692d-2059-43f8-9f2f-c3ab4924efbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a9f2af28-a7b4-42e5-a2e2-345de071fe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-icon-remover us-color-white us-iconos-card-colaborador us-hover-active</value>
      <webElementGuid>0f3da70b-98d7-47e9-bb63-c3a3625e8f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Generar Liquidación de contrato</value>
      <webElementGuid>d212c755-9b6e-40e3-9654-49e82fd4ffe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('listadoEmpleadoPrime_form',{'empleadoLiquidar':'co.com.unionsoluciones.saraprime.logica.dto.HojaEmpleadoDTO@55e77220','listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt140':'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt140'}).submit('listadoEmpleadoPrime_form');return false;</value>
      <webElementGuid>0f237d24-0d39-412d-86f7-3749204fa9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Generar Liquidación de contrato</value>
      <webElementGuid>b3778a98-9e11-4e91-9d4a-35acd919e039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt140&quot;)</value>
      <webElementGuid>676a083d-4e19-4dbe-a1b5-23800f90c8e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt140']</value>
      <webElementGuid>29cf805e-a459-4a57-8ee1-b2ba9f3b5b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='listadoEmpleadoPrime_form:tablaEmpleados_data']/tr/td/div/div[2]/div/a[2]</value>
      <webElementGuid>efca790f-8573-4514-b911-e16e4e75496f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[20]</value>
      <webElementGuid>c08f8f03-8918-40af-a000-b541fbb18afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>64e99054-1d80-49be-8b78-2cd5ec6ff684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'listadoEmpleadoPrime_form:tablaEmpleados:0:j_idt140' and @href = '#' and @title = 'Generar Liquidación de contrato']</value>
      <webElementGuid>53676d1d-604a-4197-a0d4-aae61cf49db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
