<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agregar</name>
   <tag></tag>
   <elementGuidId>de2b44e3-6882-4a33-a9fa-0f8039fc45e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[9]/div/div[2]/div[3]/span/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'us-boton' and (text() = 'Agregar' or . = 'Agregar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('popupRegistroBeneficiariosUpc_form'),{'popupRegistroBeneficiariosUpc_form:j_idt947':'popupRegistroBeneficiariosUpc_form:j_idt947'},'');return false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-boton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupRegistroBeneficiariosUpc_form:j_idt911_content&quot;)/span[@class=&quot;popupBody&quot;]/div[2]/span[@class=&quot;col-md-12&quot;]/a[@class=&quot;us-boton&quot;]</value>
   </webElementProperties>
</WebElementEntity>
