<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filtro_form_configuracionCosteoj_idt700</name>
   <tag></tag>
   <elementGuidId>11fa7e0f-37fd-4a90-b60d-931ee2661993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7aafb649-640f-49ab-9597-d87687fd6b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_configuracionCosteo:j_idt700</value>
      <webElementGuid>7f03a34b-43df-4632-a42a-20573c44a896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_configuracionCosteo:j_idt700</value>
      <webElementGuid>27c7680f-ca2c-43f4-bcb3-52e7ca8b818f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4251e4f-1fec-4d86-b328-216ab8bd611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all caja_texto ui-state-hover ui-state-focus</value>
      <webElementGuid>45c73039-41eb-4296-a562-719f14818a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_configuracionCosteo:j_idt700&quot;,e:&quot;valueChange&quot;,f:&quot;form_configuracionCosteo&quot;,p:&quot;form_configuracionCosteo:j_idt700&quot;,u:&quot;form_configuracionCosteo:panelTablaLineaCosto&quot;});</value>
      <webElementGuid>510b91c8-e122-4aa4-bf0b-551c06c4bfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8f050ead-ed34-47cf-9c44-a635424fcce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6db9600-b261-47db-9ac9-61ba61dae8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>33275555-b9fa-47dd-bc85-408c85e38ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_configuracionCosteo:j_idt700&quot;)</value>
      <webElementGuid>8e4bbad3-fad8-411f-a355-504090171703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_configuracionCosteo:j_idt700']</value>
      <webElementGuid>1260c0c1-f3fa-4590-be79-02a5f7f0797e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_configuracionCosteo:j_idt697_content']/input</value>
      <webElementGuid>abf49401-4f08-4a80-9993-03dcfded4709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>96490b25-6907-4afb-b3c2-d867361ec988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_configuracionCosteo:j_idt700' and @name = 'form_configuracionCosteo:j_idt700' and @type = 'text']</value>
      <webElementGuid>f076bfe4-9f59-41c4-9ac4-cd4331e85d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
