<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Administrador_masivo_cerrar_menu</name>
   <tag></tag>
   <elementGuidId>923754ca-b7f7-45c2-8b8c-67880adb882e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cerrar_menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e26ef46-388e-4bfe-8691-f7db1d6a1c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cerrar_menu</value>
      <webElementGuid>ae41820c-2d25-458e-981a-ae901324c347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-chevron-right us-cl-primario us-boton-menu movimiento</value>
      <webElementGuid>9a9379eb-2d25-4324-b7f2-f83bfe661b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cerrar_menu&quot;)</value>
      <webElementGuid>ee4b4815-effa-4982-908c-5fa2c25f27b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cerrar_menu']</value>
      <webElementGuid>cf120730-6db0-4cf2-9d25-7801a656f2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='j_idt71']/div/a</value>
      <webElementGuid>4ccc981f-37f2-4a69-a815-3475d7534875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>3e0a4933-4ac7-4cc8-8e42-1df5a33e7c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cerrar_menu']</value>
      <webElementGuid>36bba528-9dd9-4863-9312-235d180a118c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
