<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Corte_listado_nominaelectronicaj_idt95</name>
   <tag></tag>
   <elementGuidId>4a943b8e-ed34-4090-b58b-74e135f9e6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>512eb9e9-d611-44e0-a5e6-4d1e2f6be38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listado_nominaelectronica:j_idt95</value>
      <webElementGuid>9cb18d00-a0d7-497c-8c02-7d3c7137445e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listado_nominaelectronica:j_idt95</value>
      <webElementGuid>59229757-4edf-434d-ab0c-0ff8ae158dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96b21f47-1f73-421d-bddf-1b4b0003c133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>9670881e-e9c6-4719-bf35-94d924133682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ace_valor_campo_estandar ui-state-filled ui-state-hover ui-state-focus</value>
      <webElementGuid>adc72dc7-37ef-43e7-8618-e886fe87b75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>97f04236-0f73-4a89-a6bc-3a70002964d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>caaa661e-cb01-46cf-9a2a-fd2e2030b3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>458e0ab6-b27d-434d-a177-2bd03210fded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;listado_nominaelectronica:j_idt95&quot;,e:&quot;valueChange&quot;,f:&quot;listado_nominaelectronica&quot;,p:&quot;listado_nominaelectronica:j_idt95&quot;,u:&quot;listado_nominaelectronica:listaNominaElectronica&quot;});</value>
      <webElementGuid>5ccbdcc4-daef-4385-8d2e-b6dbef9785a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ec544f9a-9687-40aa-b43b-9bc06f36237b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f21aebe-3279-4d6b-96a9-4b8eab345065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>887ece11-e8cc-43b7-824f-7a43779a75e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listado_nominaelectronica:j_idt95&quot;)</value>
      <webElementGuid>8b00c395-36c4-4aff-87d0-95155e775b2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='listado_nominaelectronica:j_idt95']</value>
      <webElementGuid>4d3bfd7f-692d-4a00-8461-b887900c4aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listado_nominaelectronica:formPanel_content']/table/tbody/tr/td[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c5f11ab3-614c-4c1b-990d-e29db18adf38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>50233d78-220c-46bb-a3b9-19f1f82dfe65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'listado_nominaelectronica:j_idt95' and @name = 'listado_nominaelectronica:j_idt95' and @type = 'text']</value>
      <webElementGuid>6797fc96-4046-4eb8-9ed3-36731c0d5277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
