<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_faxutrameize-5298yopmail.comloginfaxutrameize-5298</name>
   <tag></tag>
   <elementGuidId>89f1f78f-1f1a-414c-8005-e5b7d5cb4920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#egen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d4938a1-071d-47ec-bef9-8ae7cbd26585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>egen</value>
      <webElementGuid>d669a8e4-5613-4028-ac49-d092b99ba501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>faxutrameize-5298@yopmail.comlogin='faxutrameize-5298'; </value>
      <webElementGuid>f72adebb-af90-42b8-a719-993ac20be20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;egen&quot;)</value>
      <webElementGuid>06b0c21e-4c59-4ec8-8fa1-c86bb6dab3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='egen']</value>
      <webElementGuid>0bc18b20-bc67-4568-a69c-83c9d2032d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su correo electrónico autogenerado'])[1]/following::div[3]</value>
      <webElementGuid>c738f4ed-103a-4f91-954e-6e425c73bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generador de correo electrónico'])[1]/following::div[6]</value>
      <webElementGuid>ab2f2d56-d0cd-4121-87fb-9b81413edab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>a4913c24-5b3e-4b2a-841a-e5c650c7fc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo'])[1]/preceding::div[1]</value>
      <webElementGuid>aa342d69-a060-428b-ab31-d468c378f025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='faxutrameize-5298@yopmail.com']/parent::*</value>
      <webElementGuid>179867df-a816-449f-a68f-260bb9a21679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[2]/div/div/div</value>
      <webElementGuid>f5a36288-c209-4f71-b459-b2a60cc0644c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'egen' and (text() = concat(&quot;faxutrameize-5298@yopmail.comlogin=&quot; , &quot;'&quot; , &quot;faxutrameize-5298&quot; , &quot;'&quot; , &quot;; &quot;) or . = concat(&quot;faxutrameize-5298@yopmail.comlogin=&quot; , &quot;'&quot; , &quot;faxutrameize-5298&quot; , &quot;'&quot; , &quot;; &quot;))]</value>
      <webElementGuid>6a99b370-bcc1-4501-b2d9-5eba09370edd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
