<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1657033250512</name>
   <tag></tag>
   <elementGuidId>7ac812b5-e541-481d-96f3-a46752326cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//body/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ce3b5636-8fa8-4db7-bc74-e4928b46e2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657033250512</value>
      <webElementGuid>c35ec807-8cd1-416d-8837-b6e94e3ac1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/1.0_crear_empresa/Frame_1657033191744</value>
      <webElementGuid>ab69c90a-f0b8-423f-8734-4d6ef791e55a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
