<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmar Clave_form_crear_cuentaconfirmarClave</name>
   <tag></tag>
   <elementGuidId>4d92321a-314a-43d4-852e-8131e299da22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'form_crear_cuenta:confirmarClave' and @type = 'password' and @name = 'form_crear_cuenta:confirmarClave']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_crear_cuenta:confirmarClave']</value>
      <webElementGuid>40fb85d3-f2cc-4c77-a67b-01bc6d2409a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_crear_cuenta']/div/div[3]/div/div/div[4]/input</value>
      <webElementGuid>47839087-b33e-4d02-acf2-33e2a7c636a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>bdfcad05-ad8e-43b7-a85c-5888bee8104c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_crear_cuenta:confirmarClave' and @type = 'password' and @name = 'form_crear_cuenta:confirmarClave']</value>
      <webElementGuid>82828e4b-a8dd-4570-89bb-bb5fb44cd4a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
