<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selecciona el plan ideal para tu empresa_form_registro_planes_producciontipoPagoPlan(pagoanual)</name>
   <tag></tag>
   <elementGuidId>5bf466da-b20d-44bc-b43a-eedec894b441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c490de19-e0a4-4d65-961c-5f9004fc4ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>65acaa3d-38ce-48a9-9e09-28d374dfb71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_registro_planes_produccion:tipoPagoPlan</value>
      <webElementGuid>8713efc5-a7c0-4e8e-bf21-6404fd779d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_registro_planes_produccion:tipoPagoPlan:0</value>
      <webElementGuid>abea1240-bb9e-4064-88b8-70de291c2926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>b8990afc-f3df-444d-a992-da785fd66787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;change&quot;,f:&quot;form_registro_planes_produccion&quot;,p:&quot;form_registro_planes_produccion:tipoPagoPlan&quot;,u:&quot;form_registro_planes_produccion:tablaPlanesMensuales&quot;});</value>
      <webElementGuid>cbbf6d7f-9048-4e26-8928-886417d1f338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_registro_planes_produccion:tipoPagoPlan:0&quot;)</value>
      <webElementGuid>0caee1ee-c608-4498-ae49-04bc032c0b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_registro_planes_produccion:tipoPagoPlan:0']</value>
      <webElementGuid>ef7042e3-3c10-40c3-8b41-6fd8ff90b84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_registro_planes_produccion:tipoPagoPlan']/tbody/tr/td/input</value>
      <webElementGuid>62a23fcb-fb08-42f2-84a3-d774e7c0da08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>02cb28bf-963d-4fae-ad96-d953469c6e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'form_registro_planes_produccion:tipoPagoPlan' and @id = 'form_registro_planes_produccion:tipoPagoPlan:0']</value>
      <webElementGuid>bee40e2c-b6b5-442c-a973-5a2d109b9e5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
