<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin_form_crear_cuentadireccion</name>
   <tag></tag>
   <elementGuidId>fb9ab7a8-6584-497a-bcd2-f6368ac64123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33a66585-2fb5-4bf6-888e-2d07b74acf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_crear_cuenta:direccion</value>
      <webElementGuid>2321ea88-eb7d-482e-b181-0650b233a6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdf9edaf-1d63-4574-b274-fb1c1fb6b2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_crear_cuenta:direccion</value>
      <webElementGuid>873a9dbb-e9b3-49c7-8a5c-fbe944266a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valor_campo_estandar</value>
      <webElementGuid>e51873eb-dabe-47ea-bbf9-663683aceafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>089c5870-bc0b-4836-99d3-a86cc09cc5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crear_cuenta:direccion&quot;)</value>
      <webElementGuid>7fb39ddd-79b8-459d-a6a8-7ac0feddc57c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_crear_cuenta:direccion']</value>
      <webElementGuid>aa0475e7-c42d-49b2-8108-44604df5f69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_crear_cuenta']/div/div[2]/div/div[4]/div[2]/input</value>
      <webElementGuid>996b9cd0-1513-4d09-a8e3-98fd0e00ff8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>79c7cfad-b92a-4f90-ad11-7dea4eae0b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_crear_cuenta:direccion' and @type = 'text' and @name = 'form_crear_cuenta:direccion']</value>
      <webElementGuid>6d3d35ec-194c-473e-a088-876fe066bc01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
