<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trabaja Sbado_form_informacionEmpresasabHabil</name>
   <tag></tag>
   <elementGuidId>ea74e56a-4d52-4d27-b832-01683c585227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div[2]/table/tbody/tr/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a262e0f-cd2e-41c6-b7ae-09eebcc0b54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2f6dfc94-2f3e-4116-a8dd-795975edb2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>a80fe45a-1b77-4c46-b1cb-327f2db6a80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_informacionEmpresa:sabHabil</value>
      <webElementGuid>7409f8ac-aa3b-4616-bc04-081c5455183a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_informacionEmpresa:sabHabil:0</value>
      <webElementGuid>cd6d7234-7e69-41bc-8a38-f505cf9b19ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>6cdb3951-d952-4a2d-a062-f7ac45d7ceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;change&quot;,f:&quot;form_informacionEmpresa&quot;,p:&quot;form_informacionEmpresa:sabHabil&quot;,u:&quot;form_informacionEmpresa:sabHabil&quot;});</value>
      <webElementGuid>eb6abcc3-36e2-4e4f-b2d8-75c0c67cfcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_informacionEmpresa:sabHabil:0&quot;)</value>
      <webElementGuid>af2c5424-d573-4c5f-a19c-8fbe677093ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2b238c0-081e-4ec3-afc2-e169d21c7d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bcdbddea-407b-4a05-9cc6-4bbd09726b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>3e4c7fa7-22da-4356-a023-28086cfce187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_informacionEmpresa:sabHabil</value>
      <webElementGuid>2b7614a8-7d47-4878-a972-1d8eacbecb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_informacionEmpresa:sabHabil:0</value>
      <webElementGuid>41bceef4-7f7a-4200-8503-f249e5a19fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>49aedc98-b0aa-4219-9cbc-d38183793349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;change&quot;,f:&quot;form_informacionEmpresa&quot;,p:&quot;form_informacionEmpresa:sabHabil&quot;,u:&quot;form_informacionEmpresa:sabHabil&quot;});</value>
      <webElementGuid>9f065ca8-12ac-4d94-8ca1-cb31d4df259d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_informacionEmpresa:sabHabil:0&quot;)</value>
      <webElementGuid>f2887333-1deb-4fc4-8910-4c8eb086370b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_informacionEmpresa:sabHabil:0']</value>
      <webElementGuid>bc66fc2c-cd3b-492f-a224-49db77de3671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_informacionEmpresa:sabHabil']/tbody/tr/td/input</value>
      <webElementGuid>81f71b8c-9eb8-47d3-b6e4-13e8eee46f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>3c7a58d1-aac7-40f5-9c0d-f778c9fd2095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @checked = 'checked' and @name = 'form_informacionEmpresa:sabHabil' and @id = 'form_informacionEmpresa:sabHabil:0']</value>
      <webElementGuid>b0c6aaac-d35c-47ac-8c2f-ce9babd8463f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
