<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre o Razon Social_form_crear_cuentanombre_razon_social</name>
   <tag></tag>
   <elementGuidId>4ce08812-afe5-422f-92ac-233a55c2ec2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5632c541-874b-4733-9a28-4922b88d4311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_crear_cuenta:nombre_razon_social</value>
      <webElementGuid>1d493597-a4bb-4a0c-87c3-02721a04c50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b49a60e1-0de0-4a80-b6be-d08d951cf087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_crear_cuenta:nombre_razon_social</value>
      <webElementGuid>d9b5461d-9bb5-4048-8dc5-54404ab3618d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valor_campo_estandar</value>
      <webElementGuid>ace6dd3a-37ff-488a-a82b-0ebf6448784c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6303384f-4b2d-402f-88cf-1256a622083a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crear_cuenta:nombre_razon_social&quot;)</value>
      <webElementGuid>cc4a85e0-8434-4982-9825-c844a520cb60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_crear_cuenta:nombre_razon_social']</value>
      <webElementGuid>aeb9a323-ae91-4d6c-8b68-6f9e9ed8567d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_crear_cuenta']/div/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>e8beada7-4b94-4225-830b-1d921ba5416b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>1d4e1043-1fed-427e-b83f-5071175d6f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_crear_cuenta:nombre_razon_social' and @type = 'text' and @name = 'form_crear_cuenta:nombre_razon_social']</value>
      <webElementGuid>db158976-40d5-492f-a414-ee70e1ce0d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
