<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Tipo de Cuenta</name>
   <tag></tag>
   <elementGuidId>ed984ed1-4346-40a9-b654-4a5a17f7316c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/span/div/form/div/div[3]/div/div[3]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>93aeea22-fee4-438f-aac2-365585031a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657056520420</value>
      <webElementGuid>e90c4b17-508a-474f-8ed9-8052f30f4e3d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
