<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ConsolidadoEspecialSucursalUnica</name>
   <tag></tag>
   <elementGuidId>517acbfc-66ca-4417-93f9-bdd3c7188849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[7]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='form_informacionEmpresa:planillaseguridad']</value>
      <webElementGuid>aacbf0ad-9b54-4344-a7cf-af4ace136620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_informacionEmpresa:panelPlanilla']/div[2]/select</value>
      <webElementGuid>5a94d998-eee4-4008-aed1-4c21086d5af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planilla Seguridad Social *'])[1]/following::select[1]</value>
      <webElementGuid>aa6053f4-aa4f-4c1d-a712-1beb3c70a967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARL *'])[1]/following::select[2]</value>
      <webElementGuid>752fe53a-627f-4230-b418-44c0801446e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja De Compensación *'])[1]/preceding::select[1]</value>
      <webElementGuid>55d102e2-34ff-4231-8fee-b4eaac879e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entidad'])[1]/preceding::select[1]</value>
      <webElementGuid>d4b29de3-0e13-4a7f-92f1-8cad7f5de37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/select</value>
      <webElementGuid>c6945ac2-64f1-4e9b-b01d-f908098e8e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'form_informacionEmpresa:planillaseguridad' and @name = 'form_informacionEmpresa:planillaseguridad' and (text() = '	Consolidado
	Especial
	Sucursal
	Unica
' or . = '	Consolidado
	Especial
	Sucursal
	Unica
')]</value>
      <webElementGuid>77c66435-e747-4459-94c0-1b661d143190</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
