<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_operador</name>
   <tag></tag>
   <elementGuidId>e373a2fc-8e6e-4d70-874c-953022044c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/span/div/form/div/div[3]/div/div[4]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4c0d5f4c-7db7-40dd-8763-bba0d01d59dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657056559573</value>
      <webElementGuid>a6b26307-0ac3-4aea-9ea6-a217071acd7c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
