<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Span_SI pago anticipado de vacaciones</name>
   <tag></tag>
   <elementGuidId>62c00a01-d7c7-4c9c-8ebc-f272fc0a7891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[2]/span/div/form/div/div[3]/div/div[7]/div[2]/table/tbody/tr/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8e9c227a-a3d6-45d8-9948-5a74123171fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657058403005</value>
      <webElementGuid>88b06722-24a8-4cd0-9100-1b805093475d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
