<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Span_Si la empresa reconoce el 33 2</name>
   <tag></tag>
   <elementGuidId>24e2a5fc-1a16-4317-a952-ea4ce8172e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//body/div[1]/div[1]/div[2]/span/div/form/div/div[3]/div/div[8]/div[2]/table/tbody/tr/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>60a31b0e-a964-4435-b402-c62adf96bbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657058530024</value>
      <webElementGuid>d51bc4c9-60a3-4cc5-87af-b5eaaeda4d4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
