<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dias 1.0  Desde01052021_formulario_nominaj_idt3207verCambioEmpleado8</name>
   <tag></tag>
   <elementGuidId>7e897650-8c45-4039-b49f-257a54834bdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[8]/td[7]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b210595-39b4-412c-8e59-ae27c91a0ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:7:verCambioEmpleado</value>
      <webElementGuid>73b54dd7-b064-45f0-985b-e7e490bd7fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>91ee9b0a-df12-4def-bc39-8c7e21e6fb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-user-add</value>
      <webElementGuid>e4ffe49a-d250-43d6-9843-780f3196cf16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('formulario_nomina',{'formulario_nomina:j_idt320:7:verCambioEmpleado':'formulario_nomina:j_idt320:7:verCambioEmpleado','empleadoVer':'co.com.unionsoluciones.saraprime.logica.dto.EmpleadoPeriodoNominaDTO@3089a386'}).submit('formulario_nomina');return false;</value>
      <webElementGuid>7781dda7-02d3-485c-9d3a-7fc8db4411ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:7:j_idt347</value>
      <webElementGuid>3f3339f8-80ac-4cdb-8ca6-3ae0658df0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_nomina:j_idt320:7:verCambioEmpleado&quot;)</value>
      <webElementGuid>0adfd031-e82b-4d29-9b56-e0d3e0948c16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formulario_nomina:j_idt320:7:verCambioEmpleado']</value>
      <webElementGuid>793fee17-505c-470d-8e6a-8269684f8f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formulario_nomina:j_idt320_data']/tr[8]/td[7]/a[3]</value>
      <webElementGuid>696d8b1a-ad11-40e1-8413-4d9e95f0a2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[75]</value>
      <webElementGuid>9103c06f-49a2-48c6-9ff4-a6cb0e0a0e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[7]/a[3]</value>
      <webElementGuid>7c016013-9145-4fef-8263-91e386524299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formulario_nomina:j_idt320:7:verCambioEmpleado' and @href = '#']</value>
      <webElementGuid>90cbf821-fe69-408c-81cd-d6eb75308b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
