<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dias 1.0  Desde01052021_formulario_nominaj_idt3208verCambioEmpleado9</name>
   <tag></tag>
   <elementGuidId>eb5dfddf-5ccd-4b70-b4ca-3a3170ac885a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[9]/td[7]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00ca75b6-4b3d-43d0-b061-b923990954b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:8:verCambioEmpleado</value>
      <webElementGuid>aeae99af-ada1-4916-8bd7-6e26a24cec87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e615b969-1d37-40e4-b725-ee92a5e76617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-user-add</value>
      <webElementGuid>afba73a8-e9bb-4212-9809-3b6b0a9b8676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('formulario_nomina',{'formulario_nomina:j_idt320:8:verCambioEmpleado':'formulario_nomina:j_idt320:8:verCambioEmpleado','empleadoVer':'co.com.unionsoluciones.saraprime.logica.dto.EmpleadoPeriodoNominaDTO@f5d44f6'}).submit('formulario_nomina');return false;</value>
      <webElementGuid>7f3b4987-c095-46be-88fa-1ca6c8dea630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:8:j_idt347</value>
      <webElementGuid>bac5dd1d-e5dc-43af-9da9-a882cd3e8925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_nomina:j_idt320:8:verCambioEmpleado&quot;)</value>
      <webElementGuid>850829d6-6bb6-454d-9de3-cf5f48d64d45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formulario_nomina:j_idt320:8:verCambioEmpleado']</value>
      <webElementGuid>8ea42abe-f561-4715-beb5-8a1583032966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formulario_nomina:j_idt320_data']/tr[9]/td[7]/a[3]</value>
      <webElementGuid>a4ac6ef0-48e1-4d5e-9ef4-e03b2b6b612a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[81]</value>
      <webElementGuid>0815a5c7-abfe-4827-9982-5a2386f4ab2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[7]/a[3]</value>
      <webElementGuid>1c55f6ed-fc47-4c4b-b651-67e475847a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formulario_nomina:j_idt320:8:verCambioEmpleado' and @href = '#']</value>
      <webElementGuid>1dcd23f7-828f-4008-a4b6-d9bc08b564ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
