<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PENSION_formulario_nominaj_idt3204verCambioEmpleado5</name>
   <tag></tag>
   <elementGuidId>d6ad9f0a-d2fd-4ffb-83d9-481939fc380d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[5]/td[7]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>053f2f85-760d-4d8b-9f92-0135462294b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:4:verCambioEmpleado</value>
      <webElementGuid>5202ad1d-9f9c-4b02-83dc-f122e37ad975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a39df386-1099-41b2-b6f4-fe0f2ea668f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-user-add</value>
      <webElementGuid>8212b1d8-f647-4c06-b28f-4794791808d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('formulario_nomina',{'empleadoVer':'co.com.unionsoluciones.saraprime.logica.dto.EmpleadoPeriodoNominaDTO@59fcd2eb','formulario_nomina:j_idt320:4:verCambioEmpleado':'formulario_nomina:j_idt320:4:verCambioEmpleado'}).submit('formulario_nomina');return false;</value>
      <webElementGuid>dabc9d67-595f-4dbf-9e7c-5b2bad31efdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt320:4:j_idt347</value>
      <webElementGuid>f2b49154-efad-4c94-bf77-5f82fdbd8437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_nomina:j_idt320:4:verCambioEmpleado&quot;)</value>
      <webElementGuid>437f6f03-73c2-4794-b936-2e98461a3e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formulario_nomina:j_idt320:4:verCambioEmpleado']</value>
      <webElementGuid>c81190fd-c931-449b-936f-20069d4da387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formulario_nomina:j_idt320_data']/tr[5]/td[7]/a[3]</value>
      <webElementGuid>05911577-ba3d-4abd-80fd-c0e39020996e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[57]</value>
      <webElementGuid>99ccf951-fa75-4dab-9302-0ac05e6895e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[7]/a[3]</value>
      <webElementGuid>f5a735cf-1e78-4386-ac07-f7821a4a37bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formulario_nomina:j_idt320:4:verCambioEmpleado' and @href = '#']</value>
      <webElementGuid>c83b77c4-17e8-48fc-a534-b9ee6a02bdbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
