<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NO_sabado_habil</name>
   <tag></tag>
   <elementGuidId>15911f8d-0755-4247-a9d5-71d12d63d31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/span/div[2]/div/form[4]/div/div[2]/div[4]/div[2]/table/tbody/tr/td[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
