<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Generar</name>
   <tag></tag>
   <elementGuidId>2a2f9ddc-cf75-4ffd-891f-9cfacc703a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Generar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97cd5177-77f3-41ba-9e20-423f059d588a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomina_electronica:j_idt122:j_idt124:j_idt625</value>
      <webElementGuid>f18c7072-049e-4057-8db9-c31af1c33d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a7976e41-752f-4b1e-80ac-83290ffa31f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget</value>
      <webElementGuid>0b00a453-ee8c-41fb-a608-6b3e7b8e3a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;nomina_electronica:j_idt122:j_idt124:j_idt625&quot;,f:&quot;nomina_electronica&quot;,u:&quot;areaAplicacion&quot;,onco:function(xhr,status,args,data){;}});return false;</value>
      <webElementGuid>e088e33c-6a7f-478a-b08b-f03b3a4f6360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;nomina_electronica:j_idt122:j_idt124:j_idt625&quot;,type:&quot;dialog&quot;,escape:true,header:&quot;Generar&quot;,message:&quot;DESEA CONFIRMAR&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>80e17254-89fa-46fd-9078-be7f7a041ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar </value>
      <webElementGuid>ff63e215-a7b7-4c50-bed8-4123629cfbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomina_electronica:j_idt122:j_idt124:j_idt625&quot;)</value>
      <webElementGuid>539f7c0d-0c08-409e-bc07-9756752e85b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nomina_electronica:j_idt122:j_idt124:j_idt625']</value>
      <webElementGuid>db582f86-5e70-4199-af04-a7c114e1bb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nomina_electronica:j_idt122:j_idt124:j_idt620']/table/tbody/tr/td/a</value>
      <webElementGuid>ade3db91-c419-4f81-bde4-cc4dbcda8ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Generar')]</value>
      <webElementGuid>527045f8-154b-4381-8bf0-4819f58c4df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomina Electronica'])[1]/following::a[1]</value>
      <webElementGuid>3933ff86-4f8a-45a1-9ca0-83c39c074b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nómina Electrónica'])[2]/following::a[1]</value>
      <webElementGuid>499f5629-10b8-432a-8152-0242162361f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Plantilla'])[1]/preceding::a[10]</value>
      <webElementGuid>5956b183-32d4-4cd2-8e89-f7c599fb83ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año'])[1]/preceding::a[10]</value>
      <webElementGuid>e92128b4-1185-4ea6-af4c-e58ab587f6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar']/parent::*</value>
      <webElementGuid>92d858a2-5453-4eba-8486-28d50029e767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[14]</value>
      <webElementGuid>e390db28-eb4f-49c0-b3e9-2b8762f64d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>8cbf6f41-c92f-4581-894a-aed9b829002d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nomina_electronica:j_idt122:j_idt124:j_idt625' and @href = '#' and (text() = 'Generar ' or . = 'Generar ')]</value>
      <webElementGuid>22ef822f-0aef-4264-a3af-e6ea8969a101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
