<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nómina Electrónica</name>
   <tag></tag>
   <elementGuidId>5a8346ce-2b40-4b74-84f2-1bad326e85d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Nómina Electrónica']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0bdb63ba-b098-4d98-8e74-dc84b19e604e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5c6f0f4f-93d7-4cb3-bdcb-e1d95a8ca5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.ab('j_idt56:main',event,'click','@this',0,{'params':{'co.com.unionsoluciones.custommenu.url':'035c5509f5d8454a9500fc4379fb2593'}}); return false</value>
      <webElementGuid>81569831-b4fa-4d21-808f-5e6f98287cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Colaboradores</value>
      <webElementGuid>e66d1afe-220a-452f-9136-d310a8b11169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt56:main&quot;)/ul[@class=&quot;us-main-menu&quot;]/li[@class=&quot;principales&quot;]/a[1]</value>
      <webElementGuid>2cfa5adb-6971-40e6-a1c5-dc3bd5fa79ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.ab('j_idt56:main',event,'click','@this',0,{'params':{'co.com.unionsoluciones.custommenu.url':'035c5509f5d8454a9500fc4379fb2593'}}); return false&quot;]</value>
      <webElementGuid>1e580622-8b11-4568-9d63-f1566a22cd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='j_idt56:main']/ul/li[8]/a</value>
      <webElementGuid>f984c54e-2516-4e82-aac4-8fc8f878b40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Colaboradores')]</value>
      <webElementGuid>d7d2d8b5-32af-4fcf-8e8d-6f279de4af05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insumos Medicos Comfama Sas'])[2]/following::a[8]</value>
      <webElementGuid>686d1936-693f-4e36-a089-5f7493153c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMILIA VARGAS MARTINEZ'])[2]/following::a[8]</value>
      <webElementGuid>5732f1e0-d8b4-43f7-afb7-1247d1f51441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenido a'])[1]/preceding::a[1]</value>
      <webElementGuid>dd0f2a86-eb8a-4d03-a077-bd4b3c1f0c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SARAPRIME'])[1]/preceding::a[1]</value>
      <webElementGuid>0f510c1d-fc63-4f3f-97a5-be3cc204e2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Colaboradores']/parent::*</value>
      <webElementGuid>b6a49cfa-3965-44bc-8865-6b5a2e4f1f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>f07c78e8-bc3b-4698-999d-ba68bcbb2075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>a49fad5f-9fd5-47f1-9f49-84ba091a02ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
