<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TestSetID_popupIngresarTestIDcodigoTest</name>
   <tag></tag>
   <elementGuidId>dfe176b0-4d14-4772-9dcb-cdae8300ed24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//body/div[1]/div[2]/span/form[2]/div/div[2]/span[1]/span[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d01f419d-acc2-4ead-b68d-8341c4cba9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupIngresarTestID:codigoTest</value>
      <webElementGuid>51349690-f735-4f19-aef6-d05b3a7c715f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ecbe1f6-a04e-41b8-bd80-39a60a64c27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupIngresarTestID:codigoTest</value>
      <webElementGuid>15b5c630-35f8-40a3-8916-dc6c07a40399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>e45ca0c5-43a1-4805-b269-df712e5498e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupIngresarTestID:codigoTest&quot;)</value>
      <webElementGuid>761fa4f5-d655-4abd-be93-b8f8721a9299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popupIngresarTestID:codigoTest']</value>
      <webElementGuid>bf8e98a5-e0d8-44e7-b9f2-a6cff5b5bc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='popupIngresarTestID:testIdDian']/span[2]/input</value>
      <webElementGuid>5aedf4db-4bc0-4927-8c51-053fb8e9865c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>37f8f825-912e-4fc2-9907-7495f7591e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popupIngresarTestID:codigoTest' and @type = 'text' and @name = 'popupIngresarTestID:codigoTest']</value>
      <webElementGuid>d510f366-506f-4ec2-a0b6-4ac976864e7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
