<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TestSetID_popupIngresarTestIDcodigoTest</name>
   <tag></tag>
   <elementGuidId>dfe176b0-4d14-4772-9dcb-cdae8300ed24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba85fa63-eca2-439e-828a-9e1e82ab4250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupIngresarTestID:codigoTest</value>
      <webElementGuid>753f15d0-3110-48ba-9b93-ea0aa7b11dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51113927-eafa-40ff-8537-41e26e9fc60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupIngresarTestID:codigoTest</value>
      <webElementGuid>6fa30fbc-c067-4294-8e8e-beb0017f62a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>ff6fe295-b685-4f37-ae4d-95bc537cea19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupIngresarTestID:codigoTest&quot;)</value>
      <webElementGuid>a07cc2e7-d8f0-4a7c-bc20-1096ce008ac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popupIngresarTestID:codigoTest']</value>
      <webElementGuid>7204e071-d72b-4fc3-8096-fc28605ae483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='popupIngresarTestID:testIdDian']/span[2]/input</value>
      <webElementGuid>a2312d02-4322-480e-9928-36c03a83599a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>b604ff9b-f72d-450f-82ba-5bf2ce2026f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popupIngresarTestID:codigoTest' and @type = 'text' and @name = 'popupIngresarTestID:codigoTest']</value>
      <webElementGuid>3bae79f9-4e81-4f5d-ac91-ddd75e5ebc6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
