<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_No se encontraron registros_form_crearNuevaEmpresaInfocamposEntidadj_idt199</name>
   <tag></tag>
   <elementGuidId>5c7fc555-c217-451a-8d1a-552f6a9f2e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>755bc25b-13e8-4d41-a0b8-655028608957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_crearNuevaEmpresaInfo:camposEntidad:j_idt199</value>
      <webElementGuid>561a2edb-545e-49c4-8591-056b46dc42ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>956ce721-271f-4db1-b332-ae800b00613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn-miniadicionar</value>
      <webElementGuid>4b2ab3bb-6ab3-4cdf-9b6b-f71b199a7ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_crearNuevaEmpresaInfo:camposEntidad:j_idt199&quot;,f:&quot;form_crearNuevaEmpresaInfo&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>40885c37-87e5-4229-a4ae-405cf249f1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crearNuevaEmpresaInfo:camposEntidad:j_idt199&quot;)</value>
      <webElementGuid>7b3c688a-1683-41e8-8c86-1167e9d3f66f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_crearNuevaEmpresaInfo:camposEntidad:j_idt199']</value>
      <webElementGuid>afd6bfa1-0996-4dd3-b64a-6a0a10c3efb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tfoot[@id='form_crearNuevaEmpresaInfo:camposEntidad_foot']/tr/td[3]/a</value>
      <webElementGuid>2ef5a643-7c9d-42d2-85c3-1380249d23f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>5c6b077e-98d5-4b9f-9184-bb2c1ab0037f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>1c112ac5-e160-4e33-943e-a1411d3a1730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_crearNuevaEmpresaInfo:camposEntidad:j_idt199' and @href = '#']</value>
      <webElementGuid>46b8c91c-419b-4b2e-b958-dfe6526583dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
