<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Da De Pago_form_crearNuevaEmpresaLiqdiames</name>
   <tag></tag>
   <elementGuidId>5fa2b3a8-7645-4a1f-8946-0bc5d7681bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02e7a61d-559b-440e-8ea7-26d16211680f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_crearNuevaEmpresaLiq:diames</value>
      <webElementGuid>751d3c25-a53f-4d0c-b684-f6195be8fa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b799b284-973a-416d-b1da-c0fd17c6a292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_crearNuevaEmpresaLiq:diames</value>
      <webElementGuid>a4d413a2-9473-47ef-94f2-823c87cac9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valor_campo_estandar</value>
      <webElementGuid>ff040af5-ba8a-477c-9ce8-e7e17cfa7e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c167137d-3d99-4375-9a55-cbd9e0336acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>687fb66f-2443-4987-8ee1-21abaed6da00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;form_crearNuevaEmpresaLiq&quot;,p:&quot;form_crearNuevaEmpresaLiq:diames&quot;,u:&quot;form_crearNuevaEmpresaLiq:panelPrimeraNomina&quot;});</value>
      <webElementGuid>ee4fefa0-9279-4bea-9b7d-b0f0213a58ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crearNuevaEmpresaLiq:diames&quot;)</value>
      <webElementGuid>84a4ce40-c254-4994-93fa-b84c3b41014a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_crearNuevaEmpresaLiq:diames']</value>
      <webElementGuid>ea6b9ed0-b772-4ed4-b809-e235a0f0ae0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_crearNuevaEmpresaLiq:panelNominaMensual']/div[2]/div[2]/input</value>
      <webElementGuid>459b41f0-48fc-4ab2-869c-8cd3396f1c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8d19fb70-8e36-4c6b-84ac-d825a12d1cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_crearNuevaEmpresaLiq:diames' and @type = 'text' and @name = 'form_crearNuevaEmpresaLiq:diames']</value>
      <webElementGuid>294b3106-dd33-409c-b250-23b14a1d56b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
