<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_NO_trabaja sabado</name>
   <tag></tag>
   <elementGuidId>fc6eef98-8838-4543-b391-1f1fe023b351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[11]/div/div[2]/table/tbody/tr/td/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>91181ade-68ec-481a-96fe-b3eb92473b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>form_crearNuevaEmpresaInfo:sabHabil:0</value>
      <webElementGuid>a5d8e4b6-3c77-4e3e-a8c2-47e7a00fa1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> NO</value>
      <webElementGuid>6735e244-208e-495f-8fbf-58854ace79b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crearNuevaEmpresaInfo:sabHabil&quot;)/tbody[1]/tr[1]/td[1]/label[1]</value>
      <webElementGuid>20e51c14-3625-44b8-9168-2172cc1acebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>88a87cf9-298c-4bd5-a37b-e9695d93dfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>form_crearNuevaEmpresaInfo:sabHabil:0</value>
      <webElementGuid>43f879ef-b6ff-4cc7-adc1-7896f18c210d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> NO</value>
      <webElementGuid>f51b1a21-684b-4e0b-a587-2e0c41dc867c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crearNuevaEmpresaInfo:sabHabil&quot;)/tbody[1]/tr[1]/td[1]/label[1]</value>
      <webElementGuid>ad7d15b4-415e-46cd-95db-fd0cf7a885ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5e9248e0-6182-4661-b5ff-91a85ad03ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>form_crearNuevaEmpresaInfo:sabHabil:0</value>
      <webElementGuid>dc6ce091-7a40-4ac7-96df-3961f2c82bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> NO</value>
      <webElementGuid>5a36dbc7-0901-43e5-acdf-928c253c7a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crearNuevaEmpresaInfo:sabHabil&quot;)/tbody[1]/tr[1]/td[1]/label[1]</value>
      <webElementGuid>6045c081-df87-4900-8178-47ecb466834d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_crearNuevaEmpresaInfo:sabHabil']/tbody/tr/td/label</value>
      <webElementGuid>f463127c-83c9-44f5-951b-30febddabfff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Trabaja Sábado?'])[1]/following::label[1]</value>
      <webElementGuid>0df2af21-ed64-4047-b627-ee031a1f2334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[3]/following::label[2]</value>
      <webElementGuid>9ae5ae21-ae48-411f-9b15-fca3d09dd22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[3]/preceding::label[1]</value>
      <webElementGuid>f2627213-b6b5-4df3-a569-93c512489f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[4]/preceding::label[2]</value>
      <webElementGuid>aa2c1502-7df0-4168-883d-da998e9adde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/table/tbody/tr/td/label</value>
      <webElementGuid>3dc8e04a-f718-4502-9606-220042878777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' NO' or . = ' NO')]</value>
      <webElementGuid>d603f02d-caf5-4ab7-a546-3b7d5e5d8207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
