<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NO_incaopacidad desde 3 dia</name>
   <tag></tag>
   <elementGuidId>7eb339be-4883-4742-9d56-744647004767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8e87a6e4-0c8c-44ff-ba15-332d4f9794aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 NO</value>
      <webElementGuid>2e515778-b561-4c4f-b1c0-b68d77b6f438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_crearNuevaEmpresaLiq:incapacidad2&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>7cfebd4e-f68a-4929-b48a-75624b38c884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_crearNuevaEmpresaLiq:incapacidad2']/tbody/tr/td</value>
      <webElementGuid>fb08871a-6701-45db-9bad-c1a49f29c38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La empresa reconoce el 33% de la incapacidad de enfermedad general desde el 3 día. ? *'])[1]/following::td[1]</value>
      <webElementGuid>e6f8f2b3-ae89-4cfe-8ff7-8b49391eb07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[4]/following::td[1]</value>
      <webElementGuid>2ddc2b3f-721a-4573-882c-c18168a9bb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[6]/preceding::td[1]</value>
      <webElementGuid>891e52b1-f15b-4ee8-abf9-1a3b5994b862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/table/tbody/tr/td</value>
      <webElementGuid>b423fe4d-3756-4dea-8be8-285b6217071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
 NO' or . = '
 NO')]</value>
      <webElementGuid>f5623541-bb1d-4990-b158-0c6923ce8538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
