<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Iniciar Asistente</name>
   <tag></tag>
   <elementGuidId>e0e6d731-65e5-452f-aa71-d10dd9d6f2cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d27d5be9-8d02-473c-a24a-dff578e81dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupIniciarAsistente:j_idt439</value>
      <webElementGuid>3e15b94b-3604-443c-83ff-30c4d1ae0a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7b0bae04-000f-457f-8fad-326bc1255ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton</value>
      <webElementGuid>2e5ebd6e-bbd1-4ca9-91ad-08a45b75f003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;popupIniciarAsistente:j_idt439&quot;,f:&quot;popupIniciarAsistente&quot;,u:&quot;popupIniciarAsistente popupPasosAsistente&quot;});return false;</value>
      <webElementGuid>250ad4e8-3b80-4805-a30a-b2629bb5990f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar Asistente</value>
      <webElementGuid>249af14d-f315-42df-8897-b143e6c33c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupIniciarAsistente:j_idt439&quot;)</value>
      <webElementGuid>e0effe36-e1c2-4cb6-9c4b-d1e432db34d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='popupIniciarAsistente:j_idt439']</value>
      <webElementGuid>53f40fc3-9a76-4e81-9553-5f6e00107a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupIniciarAsistente:dialog_popupIniciarAsistenteBean_content']/div/div[2]/a</value>
      <webElementGuid>de17e6b3-81c4-4159-bf06-9f268d55ccca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Iniciar Asistente')]</value>
      <webElementGuid>d5d30ddc-d6ba-4c46-8482-50fc75de1c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenido, este es el asistente de SaraPrime'])[1]/following::a[1]</value>
      <webElementGuid>72964f6a-afe8-4f47-9d0d-9e495a864c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontró registros'])[2]/following::a[2]</value>
      <webElementGuid>f6e94490-be86-4690-a1f0-ae73b2c43b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No volver a mostrar'])[1]/preceding::a[1]</value>
      <webElementGuid>1ee2578d-e4e1-4c00-a78d-10e678d4f425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte Técnico'])[1]/preceding::a[1]</value>
      <webElementGuid>004437f7-3ef2-489b-8acc-ff6552b24362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iniciar Asistente']/parent::*</value>
      <webElementGuid>0d94346c-ffce-47d9-b8f9-b656188b6f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>112cffad-63fd-4082-b056-6252752df965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>ef6bf3c7-5d1d-42a1-b471-936b5b30a990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'popupIniciarAsistente:j_idt439' and @href = '#' and (text() = 'Iniciar Asistente' or . = 'Iniciar Asistente')]</value>
      <webElementGuid>90a8f747-ecf5-4c49-8ed3-d54803f3a28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
