<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Descargar</name>
   <tag></tag>
   <elementGuidId>7aee6497-a900-4fc5-8ae4-2d1024ec788d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.us-boton.btn-descargar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Descargar')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7ce3f9a-5ac9-46a2-a665-ffe5e709b993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/saraprimeweb/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc63c35c37c61c31c62c35c33c37c35c62c64c34c36c32c33c61c36c35c38c37c63c64c39c64c63c39c34c66c61c66c31&amp;E=NominaElectronica.xml</value>
      <webElementGuid>65a8e728-dda4-4dd7-ab7c-e6eeed40f842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_black</value>
      <webElementGuid>ed019f97-d964-4d64-b55b-b353ac4c626c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-boton btn-descargar</value>
      <webElementGuid>530ac42d-9db7-4762-952e-757ae37aff14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descargar</value>
      <webElementGuid>60203fbe-71a2-48f4-b64c-a4a06e637489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmacionGenerar:j_idt369_content&quot;)/div[@class=&quot;us-margin-popup-btn&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;us-boton btn-descargar&quot;]</value>
      <webElementGuid>1eb76cb4-b57e-423f-8df3-e922d63ddccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmacionGenerar:j_idt369_content']/div[2]/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>571ad195-5302-4229-9579-935f2551a118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Descargar')])[3]</value>
      <webElementGuid>f75574ac-4549-4350-adb8-91ee131fe24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmación'])[1]/following::a[1]</value>
      <webElementGuid>64b257be-90b5-4382-9eee-ff18f14ec5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::a[2]</value>
      <webElementGuid>7e4fd1af-6bca-42d4-a35b-8a77e4b9d05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte Técnico'])[1]/preceding::a[1]</value>
      <webElementGuid>212f21a4-f2cd-4dee-a59e-12a5eba9d9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Union Soluciones© 2019'])[1]/preceding::a[2]</value>
      <webElementGuid>8710d13f-bf58-4992-8ccd-aaa624bb037f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/saraprimeweb/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc63c35c37c61c31c62c35c33c37c35c62c64c34c36c32c33c61c36c35c38c37c63c64c39c64c63c39c34c66c61c66c31&amp;E=NominaElectronica.xml')]</value>
      <webElementGuid>e874539a-7e77-4241-ac74-14aea224c22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/a</value>
      <webElementGuid>65148687-c643-4975-9981-ced8014e95c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/saraprimeweb/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc63c35c37c61c31c62c35c33c37c35c62c64c34c36c32c33c61c36c35c38c37c63c64c39c64c63c39c34c66c61c66c31&amp;E=NominaElectronica.xml' and (text() = 'Descargar' or . = 'Descargar')]</value>
      <webElementGuid>cc5d3f8e-94ce-4ef0-a231-e410f993d8b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
