<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Intentos_nomina_electronicatabla_detalle0j_idt158</name>
   <tag></tag>
   <elementGuidId>d3b037b4-6597-4991-8fb6-4a9923c6e0a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d74c33c1-7f9b-4f76-9753-5db9a1ce236b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomina_electronica:tabla_detalle:0:j_idt158</value>
      <webElementGuid>9f9f09f2-0a29-4ec5-86f4-6e6183b82e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectbooleancheckbox ui-chkbox ui-widget</value>
      <webElementGuid>d0553500-2b92-4ab8-8807-b51e956f4f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomina_electronica:tabla_detalle:0:j_idt158&quot;)</value>
      <webElementGuid>162bdaab-5e4e-414d-8711-cee6740079bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nomina_electronica:tabla_detalle:0:j_idt158']</value>
      <webElementGuid>b90ba998-68e0-49dd-8bdb-43fc95a71569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='nomina_electronica:tabla_detalle_data']/tr/td/div</value>
      <webElementGuid>0bc45c6b-6852-4097-8dd1-6c4b0ecb7509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intentos'])[1]/following::div[1]</value>
      <webElementGuid>822eeb9e-055c-49cf-adf8-2210ab2400e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::div[1]</value>
      <webElementGuid>7f7be552-1cd4-4a91-b437-ce6d1623f24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='. . .'])[1]/preceding::div[3]</value>
      <webElementGuid>972f37c5-c695-4f36-b035-291840b7838c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de Emisión'])[1]/preceding::div[3]</value>
      <webElementGuid>31cf0469-9322-4739-81f6-511163ae874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/div</value>
      <webElementGuid>6dd305ef-78d6-46c4-8d56-5e961bb1bc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nomina_electronica:tabla_detalle:0:j_idt158']</value>
      <webElementGuid>7f75d64f-7fff-45c0-aea0-448b7133801f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
