<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fecha fin vigencia_consultarInformacionBasica_formtablaEntidadesAPV1j_idt669_2</name>
   <tag></tag>
   <elementGuidId>f5d90b15-d1a2-47bb-b0f6-8dad87af19ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>301481eb-8a66-4b21-a813-b3523d51af07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consultarInformacionBasica_form:tablaEntidadesAPV:1:j_idt669</value>
      <webElementGuid>de8620d4-9173-46cd-ba61-7ae96adf1e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f10875f3-3969-4fe9-a6b3-858553dc5751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-icon-deleted</value>
      <webElementGuid>0b78c01a-9791-4549-9059-658023b8e58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;consultarInformacionBasica_form:tablaEntidadesAPV:1:j_idt669&quot;,f:&quot;consultarInformacionBasica_form&quot;,u:&quot;consultarInformacionBasica_form&quot;});return false;</value>
      <webElementGuid>9e225980-9c55-4b76-9de7-1e1ff6d825d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;consultarInformacionBasica_form:tablaEntidadesAPV:1:j_idt669&quot;,type:&quot;dialog&quot;,escape:true,header:&quot;Eliminar&quot;,message:&quot;Desea eliminar el   registro?&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>30138343-58eb-4467-8848-2616172d5aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consultarInformacionBasica_form:tablaEntidadesAPV:1:j_idt669&quot;)</value>
      <webElementGuid>11910939-cecf-44be-9a75-8b0b8a5646f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='consultarInformacionBasica_form:tablaEntidadesAPV:1:j_idt669']</value>
      <webElementGuid>a02bc954-a2c3-46be-80a1-734b6dbc650f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='consultarInformacionBasica_form:tablaEntidadesAPV_data']/tr[2]/td[5]/a</value>
      <webElementGuid>e26dab28-0a6b-43ac-98fc-5e12327e4d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[70]</value>
      <webElementGuid>950b8328-4fe2-40c9-b4bd-444a2a1f53cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/a</value>
      <webElementGuid>95b55f44-7d13-4ac6-81ce-a420f24a7b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'consultarInformacionBasica_form:tablaEntidadesAPV:1:j_idt669' and @href = '#']</value>
      <webElementGuid>14b61af3-def6-4c5a-a74d-104d9ebeb43d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
