<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AGUDELO ARANGO ANDREA_formulario_nominaj_idt5030verCambioEmpleado</name>
   <tag></tag>
   <elementGuidId>52acc612-bdc3-4e5d-a6c0-224a82df32ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>
/html/body/div[1]/div[2]/span/div/div/form[2]/div[3]/div[2]/div/table/tbody/tr/td[7]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c1c55ad-66d7-4572-a4e7-4a15cbf638d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_nomina:j_idt503:0:verCambioEmpleado</value>
      <webElementGuid>38cff19a-9029-4e13-926e-27d0f5ec9baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>526481a2-b37f-40ed-8d83-6d5cb63361e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-user-add</value>
      <webElementGuid>23348a92-db1b-42b6-ad51-1651c7d69f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('formulario_nomina',{'formulario_nomina:j_idt503:0:verCambioEmpleado':'formulario_nomina:j_idt503:0:verCambioEmpleado','empleadoVer':'co.com.unionsoluciones.saraprime.logica.dto.EmpleadoPeriodoNominaDTO@6ea9b824'}).submit('formulario_nomina');return false;</value>
      <webElementGuid>93ef1d96-6c6c-4e6f-9a9f-1ca3354c8919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_nomina:j_idt503:0:verCambioEmpleado&quot;)</value>
      <webElementGuid>183e0539-f85b-4f1c-9823-c06869234a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formulario_nomina:j_idt503:0:verCambioEmpleado']</value>
      <webElementGuid>a6dbd90f-58a2-4f50-b5fe-1d25ac4b9f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formulario_nomina:j_idt503_data']/tr/td[7]/a[3]</value>
      <webElementGuid>bf2c2d10-a00c-4248-b281-dd4ef732d043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[34]</value>
      <webElementGuid>6a3a801a-0ccc-41c5-ab37-f9045a9edd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>662a0cf1-e7ca-4a69-ac14-b07bc9847a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
